version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: appwoyofal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
